name: pixel_year_v1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  flutter_timezone: ^3.0.0
  intl: ^0.20.2
  fl_chart: ^0.63.0
  http: ^1.6.0
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  google_fonts: ^6.3.2
  google_translator: ^1.0.0
  translator: ^1.0.0
  lottie: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/pixel_year_v1_pixel_animations_login.json
    - assets/animations/pixel_year_v1_pixel_animations_register.json
    - assets/animations/pixel_year_v1_pixel_animations_drawer.json

